name: Update Weather

on:
  schedule:
    - cron: "0 */3 * * *" # Mỗi 3 giờ
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Weather SVG
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate weather
        uses: yanglbme/github-actions-weather@v1.2
        with:
          city: Hanoi
          unit: metric
          lang: en
          output_file: weather.svg

      - name: Commit & push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'weather.svg'
          message: 'chore: update weather'
